global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka1:9404', 'kafka2:9404', 'kafka3:9404']
  - job_name: 'kafka-monitor'
    static_configs:
      - targets: ['host.docker.internal:8080']